modLoader="javafml"
loaderVersion="[4,)"
license="Not specified"

[[mods]]
modId="health_tag"
version="1.0.0"
displayName="Health Tag"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Dreyka Oas"
description="Displays entity health as nametags"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.health_tag]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.65,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.health_tag]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration